name: Build runtime image

# Run when tag starts with "tercen/runtime"
on:
  push:
    tags:
      - '^tercen/runtime-.*_.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Check if image exists
      run: |
        echo "IMAGE_NAME=$(echo $GITHUB_REF_NAME | sed 's/_/:/')"  >> $GITHUB_ENV
        echo "IMAGE_MISSING=$(docker manifest inspect env.IMAGE_NAME > /dev/null ; echo $?)"  >> $GITHUB_ENV
        echo "DIR_NAME=$(echo env.IMAGE_NAME | grep -o -P '(?<=tercen/).*(?=_)')"  >> $GITHUB_ENV
    - name: Build docker image
      # run only if image is missing (1) 
      if: env.IMAGE_MISSING == 1
      run: |
        docker build -t env.IMAGE_NAME ./${{ env.DIR_NAME }}
    - name: docker push
      if: env.IMAGE_MISSING == 1
      run: |
        docker push env.IMAGE_NAME
